version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing AWS CLI"
      - pip install --upgrade awscli
  build:
    commands:
      - echo "Packaging LF1 Lambda function"
      - zip -r lf1-function.zip .
      - echo "Updating LF1 Lambda function code"
      - aws lambda update-function-code --function-name <LF1> --zip-file fileb://lf1-function.zip
      - echo "LF1 Lambda function updated successfully"
