version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing AWS CLI"
      - pip install awscli --upgrade
  build:
    commands:
      - echo "Packaging LF1..."
      - cp LF1 lambda_function.py  # Rename LF1 to lambda_function.py
      - zip -r lf1.zip lambda_function.py  # Package LF1 into a ZIP file
      - echo "Packaging LF2..."
      - cp LF2 lambda_function.py  # Rename LF2 to lambda_function.py
      - zip -r lf2.zip lambda_function.py  # Package LF2 into a ZIP file
      - echo "Creating AppSpec file..."
      - |
        cat <<EOF > appspec.yml
        version: 0.0
        Resources:
          - FunctionName: LF1
            FunctionAlias: LIVE
            Name: lf1.zip
          - FunctionName: LF2
            FunctionAlias: LIVE
            Name: lf2.zip
        EOF
  post_build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - appspec.yml
    - lf1.zip
    - lf2.zip
