version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - cp lambda_function.py lambda_function.py
      - zip -r lf1.zip lambda_function.py
  post_build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - appspec.yml
    - lf1.zip
