version: 0.2
phases:
  install:
    commands:
      echo: "Installing dependencies"
  build:
    commands:
      - echo "Zipping the Lambda function and AppSpec file"
      - zip -r lf1.zip lambda_function.py appspec.yml
artifacts:
  files:
    - lf1.zip
    - appspec.yml
