version: 0.0
Resources:
  - myLambdaFunction1:
      Type: AWS::Lambda::Function
      Properties:
        Name: "LF1"
        Alias: "Prod"
        CurrentVersion: "1"
        TargetVersion: "1"
  - myLambdaFunction2:
      Type: AWS::Lambda::Function
      Properties:
        Name: "LF2"
        Alias: "Prod"
        CurrentVersion: "3"
        TargetVersion: "3"
